# =========================
# BUILD STAGE
# =========================
FROM node:24-alpine AS builder

WORKDIR /app

# Copiar package para aprovechar cache
COPY package*.json ./

# Instalar dependencias
RUN npm ci

# Copiar código
COPY . .

# Generar Prisma Client
RUN npx prisma generate

# Compilar TypeScript
RUN npm run build


# =========================
# PRODUCTION STAGE
# =========================
FROM node:24-alpine AS production

WORKDIR /app

ENV NODE_ENV=production

# Copiar package
COPY package*.json ./

# Instalar solo dependencias de producción
RUN npm ci --omit=dev --ignore-scripts

# Copiar build
COPY --from=builder /app/dist ./dist

# Copiar Prisma Client generado
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma

COPY --from=builder /app/node_modules/@prisma/client ./node_modules/@prisma/client

EXPOSE 3000

CMD ["node", "dist/main.js"]