sonar.projectKey=jac2206_layer-express-ts
sonar.organization=jac2206
sonar.sources=src
sonar.tests=test
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=src/main.ts,src/server.ts,src/services/interfaces/**,src/config/**,src/routes/**,src/errors/**,src/entities/**,src/repositories/interfaces/**,src/dto/**,src/controllers/**,src/schemas/**,"src/**/*.spec.ts",src/security/**,src/utils/**,src/middlewares/**,src/validators/**,src/services/**,src/repositories/**,src/routes/**,src/config/**,src/errors/**,src/entities/**,src/dto/**,src/controllers/**
